[Testfix] Fix logging error
Problem:
Line 135 is missing () which leads to the below trace back
when the testcase fails:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file test_volume_start_stop_while_rebalance_in_progress.py, line 135
```

Solution:
Adding the missing () brackets in line 135.

Change-Id: I318a5b838f01840afee5d4109645cc7dcd86c8fa
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>